name: Node.js CI

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master  

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  

    - name: Install dependencies
      run: npm install  # Installs dependencies based on your package.json


    - name: Build the project
      run: npm run build  

    - name: Run Docker (Optional)
      run: |
        docker build -t my-app .  # Build Docker image if necessary
        docker run -d -p 5000:5000 my-app  # Run the app inside Docker

    - name: Deploy (Optional)
      run: |
        # Add your deployment steps here if needed, such as AWS, Heroku, etc.
